# ----
# Site

title: TDPW Manual #标题,用于header
url: "/" #header处url
baseurl:  #url常用site.baseurl/
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png #左侧目录处标题
description: Product documentation template for Jekyll.
author:
  name: cndaqiang
  email: who@cndaqiang.ac.cn
  twitter: # twitter username without the @ symbol
social:
  name: cndaqiang
  links:
    - http://cndaqiang.github.io/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon
#------ 应该没啥用
types:
  - minor
  - major
  - TAG0

theme: jekyll-theme-cayman